---
- name: setting proxy and install pgpool
  hosts: nodeall
  become: true

  vars:
    proxy_env:
      http_proxy: "{{ http_proxy }}"
      https_proxy: "{{ https_proxy }}"

  tasks:
    - name: install pgpool
      apt:
        name: pgpool2
        state: present
      environment: "{{ proxy_env }}"

