---
- name: create postgre directory
  hosts: nodeall
  become: true

  tasks:
    - name: create /data/pgpool directory if it does not exist
      ansible.builtin.file:
        path: /data/pgpool
        state: directory
        owner: postgres
        group: postgres
        mode: '0755'

- name: setting proxy and install pgpool
  hosts: nodeall
  become: true

  vars:
    proxy_env:
      http_proxy: "{{ http_proxy }}"
      https_proxy: "{{ https_proxy }}"

  tasks:
    - name: install pgpool
      apt:
        name: pgpool2
        state: present
      environment: "{{ proxy_env }}"

- name: copy pgpool.conf and restart pgpool
  hosts: nodeall
  become: true

  tasks: 
    - name: copy pgpool.conf
      copy: 
        src: ./files/pgpool.conf
        dest: /etc/pgpool2/pgpool.conf
        owner: root
        group: root
        mode: 0764

    - name: restart pgpool
      service:
        name: pgpool2
        state: restarted